--- # Debugging
-   hosts: '{{ myHosts }}'
    remote_user: ec2-user
    become: yes
    become_method: sudo
    connection: ssh
    gather_facts: '{{ gather }}'
    vars:
        myHosts: amazon-linux
        gather: yes
        pkg: telnet
    tasks:
    - name: Install telnet server on centos
      yum:
        name: '{{ pkg }}'
        state: latest
      register: yum_result
    - debug: var=yum_result
