--- # Debugging
-   hosts: '{{ myHosts }}'
    remote_user: ec2-user
    become: yes
    become_method: sudo
    connection: ssh
    gather_facts: '{{ gather }}'
    vars:
        myHosts: webserver
        gather: yes
    tasks:
    - shell: cat /home/ec2-user/hostname.conf
      register: hosts
    - debug: var=hosts
    - debug: msg="Hosts File is empty"  
      when: hosts.stdout == ""
