--- # Install http server and Deploy the Html File
-  hosts: amazon-linux
   remote_user: ec2-user
   become: yes
   tasks: 
      - name: Install Apache Server
        yum:
            name: httpd
            state: present
        notify:
        - startservice
      - name: create a file if does not exist
        file:
            state: touch
            path: /var/www/html/index.html
      - name: Adding line 
        lineinfile:
             state: present
             path: /var/www/html/index.html
             line: Hostname= {{ansible_hostname}}
   handlers:
    - name: startservice
      service:
         name: httpd
         state: restarted
         enabled: true
